data = ["Ify i fory.",
        "Koniec głupawki.",
        "Kita. Last call.",
        "Panowie, przedszkolak by to zrobił.",
        "KAJAKI.",
        "To nic. Od wody się nie umiera.",
        "Człowiek małej wiary 😊",
        "Ale ty nie wiesz jeszcze czy ty jesteś homo czy hetero.",
        "Filip robi noworodki.",
        "Kamil narysuj penisa.",
        "Obciąłeś sobie, Oleksandr?",
        "Ja jestem specjalnej potrzeby.",
        "Czarnuchu!",
        "Jak ktoś chce pozaciskać kable to może pozaciskać.",
        "Gdzie jest ten specjalnej potrzeby Aleks?",
        "Kamil jest gejem.",
        "To obejrzymy sobie, jak być ciekawą osobą, skierowane do Alana.",
        "Kto tu jeszcze jest specjalny? Dawid.",
        "Janek nie ładuj Pawła.",
        "Czym się różni klasyfikowanie od kastracji?",
        "Przychodzę was popodglądać.",
        "Bo ja sobie wymyśliłem rasizm.",
        "I zobacz, I teraz jest to, czy lepiej, aby od tyłu molestował, czy od przodu?"]